export const LOGIN_SUCCESS = 'LOGIN_SUCCES';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_CONTACTS_ERROR = 'GET_CONTACTS_ERROR';
export const FILTER_BY_LETTER = 'FILTER_BY_LETTER';
export const FILTER_BY_NAME = 'FILTER_BY_NAME';
export const GET_CURRENT_CONTACT = 'GET_CURRENT_CONTACT';
export const SET_PAGINATION = 'SET_PAGINATION';


