export const LOGIN_SUCCESS = 'LOGIN_SUCCES';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_CONTACTS_ERROR = 'GET_CONTACTS_ERROR';
export const FILTER_BY_LETTER = 'FILTER_BY_LETTER';